#!/bin/bash

export CXX='/usr/bin/clang++'

clean() {
	rm -rf build && mkdir build
}

cmake_refresh() {
	cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
		-DCMAKE_BUILD_TYPE=$1 \
		-S . \
		-B build
}

cmake_debug() {
	cmake_refresh DEBUG
}

cmake_release() {
	cmake_refresh RELEASE
}

lint() {
	clang-tidy -p build src/**/*.cpp include/**/*.h
}

build() {
	cmake --build build
}

run() {
	./build/nesemu
}

test() {
	./build/unit_tests
}

gen_doc() {
	doxygen ./doxygen_config
}

full() {
	clean
	cmake_debug
	lint
	gen_doc
	build
	test
}

for var in $@
do
	echo "====== $var ======"
	$var || break
done
